version: "3.9"

services:
   mysql_wordpress:
     container_name: mysql_wordpress     
     image: mysql:8.0.29
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
       MYSQL_DATABASE: ${MYSQL_DB}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASS}
     volumes:
       - db_data:/var/lib/mysql       

   wordpress:
     depends_on:
       - mysql_wordpress
     container_name: wordpress     
     image: wordpress:latest
     restart: always
     environment:
       WORDPRESS_DB_HOST: mysql_wordpress:3306
       WORDPRESS_DB_USER: ${MYSQL_USER}
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASS}
       WORDPRESS_DB_NAME: ${MYSQL_DB}       
       VIRTUAL_HOST: ${VIRTUAL_HOST}
       LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
       LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
       VIRTUAL_PORT: "80"       
     volumes:
      - wordpress_data:/var/www/html        

volumes:
    db_data:
    wordpress_data:
    
#Network do container do nginx-proxy
networks:
  default:
    external:
      name: nginx-proxy    
